# Generated by Django 3.2.16 on 2023-03-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_rename_course_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='CourseNew',
        ),
    ]
